services:
  home-gate-detection:
    build: .
    volumes:
      - ./best.onnx:/app/best.onnx
      - ./open-images:/app/open-images
      - ./closed-images:/app/closed-images
    restart: 'always'
    env_file: .env